version: '3.7'

#you can include needed services to your network using docker-compose service merging :  docker-compose -f docker-compose.yml -f docker-composer.elk.yml up

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    volumes:
      - ./:/app:cached
    depends_on:
      #      - redis
      - kafka

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "hell:10:1,oauthdata:5:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
